### ISSUE TITLE
draw_box error in Home Assistant 0.103.4

### ISSUE THREAD

**Issue by rostikk80** [robmarkcole/HASS-Google-Vision#4]
Platform error image_processing.google_vision - cannot import name 'draw_box' from 'homeassistant.components.image_processing' (/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py)

**Comment by robmarkcole** [comment]
Fixed in https://github.com/robmarkcole/HASS-Google-Vision/releases/tag/v0.4
